[package]
name = "guitar_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.4"
eframe = "0.21.3"
egui = "0.21.0"
hound = "3.5.0"
realfft = "3.3.0"
rodio = "0.17.1"
